### ISSUE TITLE
SUGGESTION [GUI]

### ISSUE THREAD

**Issue by OtasGamer64** [JorisJoriukas/scratch-username-generator#1]
There should be a GUI. Also, there should be an option to copy your username. Sounds good?

**Comment by JorisJoriukas** [comment]
Well, thanks for the suggestion. I will add it soon. This thread will be closed once the suggestion is added.

**Comment by JorisJoriukas** [comment]
Well, I can't do it, sorry :(

**Comment by ghost** [comment]
I think I can try to make a GUI, idk about the option to copy your username though
